config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :members
  namespace :admins do
    resources :members, only: [:new, :create, :index, :show, :edit,:update,:destroy]
    resources :attendance_informations
    resources :work_scheduleds,only: [:index,:show,:edit,:update,:destroy]
  end
  resources :members, only: [:show, :update]

  root to: "homes#index"

  get '/time_in', to: 'attendance_informations#time_in'
  get '/time_out', to: 'attendance_informations#time_out'

  # post '/' => 'attendance_informations#create'
  # get '/time_out' => 'attendance_informations#new'
  # patch '/time_out' => 'attendance_informations#new'
  # get '/attendance' => 'attendance_informations#index'
  # get '/attendance/:id' => 'attendance_informations#edit'
  # patch '/attendance/:id' => 'attendance_informations#update'
  # get '/attendance_informations' => 'attendance_informations#show'

  resources :work_scheduleds,only: [:index,:new,:create]
  resources :attendance_informations
  # get 'charts/index'
  resources :charts,only: [:index, :edit, :update, :destroy]

end

app/models/member.rb
class Member < ApplicationRecord
  has_many :attendance_informations,dependent: :destroy
  has_many :work_scheduleds,dependent: :destroy
  validates :member_id, uniqueness:{ message: 'メンバーIDは既に使われています' }
  validates :member_id, presence:{ message: 'メンバーIDを入力してください' }
  attachment :image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  def applying?
    attendance_informations.any?{|attendance_information|attendance_information.applying?}
  end
end

app/controllers/admins/members_controller.rb
class Admins::MembersController < ApplicationController

  before_action :authenticate_admin!

  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to admins_members_path
    else
      render :new
    end
  end

  def index
     @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update

    @member = Member.find(params[:id])
    @member.update(member_params)
    redirect_to admins_member_path(@member)
  end

  def destroy
    @member = Member.find(params[:id])
    @member.destroy
    redirect_to admins_members_path
  end

  private
  def member_params
    params.require(:member).permit(
        :member_id,
        :email, :password,
        :first_name_kana, :last_name_kana,
        :first_name, :last_name,
        :postal_code, :address,
        :phone_number
      )
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :authenticate_member!

  def show
     @member = Member.find(params[:id])
     @member_new = Member.new
  end

  def update
    @member = Member.find(params[:id])
    @member.update!(password_params)
    redirect_to member_path(@member)
  end

  private

  def password_params
    params.require(:member).permit(:password, :password_confirmation, :image)
  end
end

app/helpers/admins/members_helper.rb
module Admins::MembersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/admins/members/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h4>登録日</h4>
    </div>
     <div class="col-md-8">
     <h4><%= l @member.created_at.in_time_zone('Tokyo'), format: :original %></h4>
     </div>
  </div>
  <div class="row">
    <div class="col-md-4">
     <h4>ID</h4>
    </div>
    <div class="col-md-8">
      <h4><%= @member.member_id %></h4>
    </div>
  </div>
    <%= form_with model: @member,  url: admins_member_path(@member) , local:true do |f| %>
      <div class="row">
      <div class="col-md-4">
      <h4>メールアドレス</h4>
      </div>
      <div class="col-md-8">
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="col-md-4">
         <h4>姓</h4>
      </div>
      <div class="col-md-8">
        <%= f.text_field :first_name, class: 'form-control'%>
      </div>
      <div class="col-md-4">
       <h4>名</h4>
      </div>
      <div class="col-md-8">
        <%= f.text_field :last_name, class: 'form-control'%>
      </div>
      <div class="col-md-4">
       <h4>セイ</h4>
      </div>
      <div class="col-md-8">
      <%= f.text_field :first_name_kana, class: 'form-control'%>
      </div>
      <div class="col-md-4">
       <h4>メイ</h4>
      </div>
      <div class="col-md-8">
        <%= f.text_field :last_name_kana, class: 'form-control'%>
      </div>
      <div class="col-md-4">
        <h4>郵便番号</h4>
      </div>
      <div class="col-md-8">
        <%= f.text_field :postal_code, class: 'form-control'%>
      </div>
      <div class="col-md-4">
        <h4>住所</h4>
      </div>
      <div class="col-md-8">
        <%= f.text_field :address, class: 'form-control'%>
      </div>
      <div class="col-md-4">
        <h4>電話番号</h4>
      </div>
      <div class="col-md-8">
        <%= f.text_field :phone_number, class: 'form-control'%>
      </div>

   </div>
   <%= f.submit '修正', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/admins/members/index.html.erb
<div class="container">
     <% if admin_signed_in? %>
        <h2><%= "#{current_admin.first_name} #{current_admin.last_name}" %></h2>
    <% end %>
    <br>
    <h2>メンバー一覧</h2>
    <% if admin_signed_in? %>
        <div class="text-right mb-3">
            <%= link_to new_admins_member_path do %>
                <i class="fas fa-plus-square fa-2x"></i>
            <% end %>
        </div>
    <% end %>
    <table class="table table-hover">
        <tr>
            <th>メンバー ID</th>
            <th>名前</th>
            <th>EMAIL</th>
            <th class=>打刻カレンダー</th>
        </tr>
        <% @members.each do |member| %>
            <tr>
                <td><%= member.member_id %></td>
                <td><%= link_to admins_member_path(member) do %>
                <%= member.first_name + member.last_name %>
                <% end %>
                </td>
                <td><%= member.email %></td>
                <td class="d-flex">
                    <%= link_to admins_attendance_informations_path(member_id: member.id) do %>
                        <i class="fas fa-calendar-alt"></i>
                    <% end %>
                <% if member.applying? %>
                <div class= "mx-3"><div class="text-danger">申請あり</div></div>
                <% end %>
                </td>
            </tr>
        <% end %>
    </table>
</div>

app/views/admins/members/new.html.erb
<div class="container">
  <h2>メンバー追加</h2>
  <%= form_with model: @member, url: admins_members_path, method: :post, local: true do |f| %>
  <%= render "layouts/error_messages", errors: @member.errors %>

    <div class="form-group">
      <div class="row">
        <div class="col-md-2">
          <%= f.label :member_id ,"メンバーID" %>
        </div>
        <div class="col-md-10">
          <%= f.text_field :member_id, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-2">
          <%= f.label :email , "メールアドレス"%>
        </div>
        <div class="col-md-4">
          <%= f.email_field :email, class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= f.label :password ,"パスワード" %>
        </div>
        <div class="col-md-4">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-2">
          <%= f.label :first_name_kana , "姓カナ"%>
        </div>
        <div class="col-md-4">
          <%= f.text_field :first_name_kana, class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= f.label :last_name_kana , "名カナ"%>
        </div>
        <div class="col-md-4">
          <%= f.text_field :last_name_kana, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-2">
          <%= f.label :first_name , "姓"%>
        </div>
        <div class="col-md-4">
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= f.label :last_name , "名"%>
        </div>
        <div class="col-md-4">
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-md-2">
          <%= f.label :postal_code , "郵便番号"%>
        </div>
        <div class="col-md-3">
          <%= f.text_field :postal_code, class: "form-control" %>
        </div>
        <div class="col-md-2">
          <%= f.label :address , "住所"%>
        </div>
        <div class="col-md-5">
          <%= f.text_field :address, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-md-2">
          <%= f.label :phone_number , "電話番号"%>
        </div>
        <div class="col-md-10">
          <%= f.text_field :phone_number, class: "form-control" %>
        </div>
      </div>
    </div>

    <%= f.submit '追加', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/admins/members/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <div class="container">
  <div class="row">
    <div class="col-md-2">
      <small class="text-black-50">
       登録日
      </small>
    </div>
    <div class="col-md-10 mb-2">
      <%= l @member.created_at.in_time_zone('Tokyo'), format: :original %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
       <small class="text-black-50">
       id
       </small>
    </div>
    <div class="col-md-10">
      <%= @member.member_id %>
    </div>
    </div>
  <div class="row">
    <div class="col-md-2">
      <small class="text-black-50">
        メールアドレス
      </small>
    </div>
    <div class="col-md-7 mb-2">
      <%= @member.email %>
    </div>

  </div>
  <div class="row">
    <div class="col-md-2">
      <small class="text-black-50">
        姓
      </small>
    </div>
    <div class="col-md-4 mb-2">
      <%= @member.first_name %>
    </div>
    <div class="col-md-2">
      <small class="text-black-50">
        名
      </small>
    </div>
    <div class="col-md-4 mb-2">
      <%= @member.last_name %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2 mb-2">
      <small class="text-black-50">
       セイ
      </small>
    </div>
    <div class="col-md-4 mb-3">
      <%= @member.first_name_kana %>
    </div>
    <div class="col-md-2 mb-2">
      <small class="text-black-50">
        メイ
      </small>
    </div>
    <div class="col-md-4 mb-3">
      <%= @member.last_name_kana %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <small class="text-black-50">
        郵便番号
      </small>
    </div>
    <div class="col-md-10 mb-3">
      <%= @member.postal_code %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <small class="text-black-50">
        住所
      </small>
    </div>
    <div class="col-md-10 mb-3">
      <%= @member.address %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <small class="text-black-50">
        電話番号
      </small>
    </div>
    <div class="col-md-10 mb-3">
      <%= @member.phone_number %>
    </div>
  </div>
    </div>
  </div>
   <div class="col-md-3">
    <%= attachment_image_tag @member, :image, :fill, 100, 100 , fallback: "neko.jpg", size: "100x100" %>
   </div>
    </div>
   <%= link_to '編集', edit_admins_member_path(@member), method: :get %>
   <%= link_to '削除', admins_member_path(@member), method: :delete, data: {confirm:'本当に削除しますか？'} %>
</div>

</div>