config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :members
  namespace :admins do
    resources :members, only: [:new, :create, :index, :show, :edit,:update,:destroy]
    resources :attendance_informations
    resources :work_scheduleds,only: [:index,:show,:edit,:update,:destroy]
  end
  resources :members, only: [:show, :update]

  root to: "homes#index"

  get '/time_in', to: 'attendance_informations#time_in'
  get '/time_out', to: 'attendance_informations#time_out'

  # post '/' => 'attendance_informations#create'
  # get '/time_out' => 'attendance_informations#new'
  # patch '/time_out' => 'attendance_informations#new'
  # get '/attendance' => 'attendance_informations#index'
  # get '/attendance/:id' => 'attendance_informations#edit'
  # patch '/attendance/:id' => 'attendance_informations#update'
  # get '/attendance_informations' => 'attendance_informations#show'

  resources :work_scheduleds,only: [:index,:new,:create]
  resources :attendance_informations
  # get 'charts/index'
  resources :charts,only: [:index, :edit, :update, :destroy]

end

app/models/attendance_information.rb
class AttendanceInformation < ApplicationRecord
  belongs_to :member
  has_one :approval_history
  enum status: { applying: 0, approval: 1, nonapproval: 2 }
end

app/controllers/admins/attendance_informations_controller.rb
class Admins::AttendanceInformationsController < ApplicationController
  before_action :authenticate_admin!
  def show
    @ai = AttendanceInformation.find(params[:id])
  end

  def index
    # @month = params[:month] ? Time.parse(params[:month]) : Time.zone.today
    # start_month = @month.beginning_of_month
    # end_month = @month.end_of_month

    # @ais = AttendanceInformation.where(time_in: start_month..end_month).page(params[:page]).per(10).order('updated_at DESC')
    @ais = AttendanceInformation.where(member_id: params[:member_id])
    @member = Member.find(params[:member_id])
  end

  def update
    @ai = AttendanceInformation.find(params[:id])
    @ai.update(status: params[:status])
    if @ai.status == "applying"
      ApprovalHistory.where(attendance_information_id: @ai.id).destroy_all
      redirect_to admins_attendance_informations_path(member_id: @ai.member_id)
    elsif @ai.status == "approval"
      if !(@ai.temp_time_in.nil? || @ai.temp_time_out.nil?)
        @ai.update(time_in: @ai.temp_time_in, time_out: @ai.temp_time_out, temp_time_in: nil, temp_time_out: nil)
      end
      redirect_to new_admins_attendance_information_path(ai_id: @ai.id)
    elsif @ai.status == "nonapproval"
      redirect_to new_admins_attendance_information_path(ai_id: @ai.id)
    else
      redirect_to admins_attendance_informations_path(member_id: @ai.member_id)
    end
  end

  def new
    @reason = ApprovalHistory.new
  end

  def create
    @reason = ApprovalHistory.new(approval_history_params)
    if @reason.save
      redirect_to admins_attendance_informations_path(member_id: @reason.attendance_information.member_id)
    else
      render :new
    end
  end

  def destroy
     @ai = AttendanceInformation.find(params[:id])
     @member_id = @ai.member_id
     @ai.destroy
     redirect_to admins_attendance_informations_path(member_id: @member_id)
  end

  private

  def approval_history_params
    params.require(:approval_history).permit(:reason).merge(
      admin_id: current_admin.id,
      attendance_information_id: params[:ai_id]
      )
  end

end

app/controllers/attendance_informations_controller.rb
class AttendanceInformationsController < ApplicationController
  before_action :authenticate_member!

  def index
    params[:selected_month] = Date.today.strftime('%Y-%m') unless params[:selected_month].present?
    @ais = AttendanceInformation.where(member_id: current_member.id).reverse
    #params[:selected_month] = '2022-01'

    @ais = current_member.attendance_informations.select { |info| Date.today.all_month.include?(Date.parse(info.time_in.to_s))}
    #if Rails.env.production?
      #@ais=  AttendanceInformation.where("DATE_FORMAT('%Y-%m',time_in)='#{params[:selected_month]}'").where(member_id: current_member.id).reverse
    #else
     # @ais=  AttendanceInformation.where("strftime('%Y-%m',time_in)='#{params[:selected_month]}'").where(member_id: current_member.id).reverse
   # end
    ## pp params[:selected_month]g
    yymmdd = params[:selected_month].split('-')
    ## pp yymmdd
    @base_month = Date.new(yymmdd[0].to_i,yymmdd[1].to_i,1)

  end

  def new
    @ais = AttendanceInformation.where(member_id: current_member.id).reverse.take(5)
  end

  def show
    @ai = AttendanceInformation.find(params[:id])
  end

  def time_in
    ai = AttendanceInformation.new
    ai.member_id = current_member.id
    ai.time_in = Time.current
    ai.save
    redirect_to new_attendance_information_path
  end

  def time_out
    ai = AttendanceInformation.where(member_id: current_member.id).where.not(time_in: nil).last
    if ai.time_out.nil?
      ai.update(time_out: Time.current)
    end
    redirect_to new_attendance_information_path
  end

  def edit
    @ai = AttendanceInformation.find(params[:id])
  end

  def update
    @ai = AttendanceInformation.find(params[:id])
    @ai.update(attendance_information_params.merge(status: "applying"))
    render :edit
  end

  private
  def attendance_information_params
    params
      .require(:attendance_information)
      .permit(:temp_time_in, :temp_time_out)
  end
end

app/helpers/admins/attendance_informations_helper.rb
module Admins::AttendanceInformationsHelper
end

app/views/attendance_informations/edit.html.erb
<h3>修正ページ</h3>
<div>
  <div class="col">
    修正前

 <div class="col">
          <%= l @ai.time_in.in_time_zone('Tokyo'), format: :original %>
        </div>
        <div class="col">
          <%= l @ai.time_out.in_time_zone('Tokyo'), format: :original %>
        </div>
</div>
 </div>

 <%= form_with model: @ai, local: true do |f| %>
  <div>
  <label class="control-label" for="">出勤時間</label>
  <%= f.datetime_field :temp_time_in, value: @ai.time_in.strftime('%Y-%m-%dT%T') %>
  </div>
  <div>
  <label class="control-label" for="">退勤時間</label>
  <%= f.datetime_field :temp_time_out, value: @ai.time_out.strftime('%Y-%m-%dT%T') %>
  </div>
  <%= f.submit '修正申請', class: 'btn btn-primary' %>
<% end %>

app/views/attendance_informations/index.html.erb
<div class="container">
  <%= link_to "<-#{@base_month.last_month.strftime('%Y年%m月')}", attendance_informations_path(selected_month: @base_month.last_month.strftime('%Y-%m')) %>
  <%= link_to "#{@base_month.strftime('%Y年%m月')}", attendance_informations_path(selected_month: @base_month.strftime('%Y-%m')) %>
    <%= link_to "#{@base_month.next_month.strftime('%Y年%m月')}->", attendance_informations_path(selected_month: @base_month.next_month.strftime('%Y-%m')) %>
     <% @ais.each do |ai| %>
    <div class="row">
        <div class="col-md-4">
          <small>
            <%= l ai.time_in.in_time_zone('Tokyo'), format: :original %>
          </small>
        </div>
        <div class="col-md-4">
          <% unless ai.time_out.nil? %>
            <small>
              <%= l ai.time_out.in_time_zone('Tokyo'), format: :original %>
            </small>
          <% else %>
            <span class="text-danger">未打刻</span>
          <% end %>
        </div>
        <div class="col-md-2">
          <%= link_to attendance_information_path(ai) do %>
            <%= ai.status_i18n %>
          <% end %>
        </div>
        <div class="col-md-2">
           <%= link_to "修正",edit_attendance_information_path(ai) %>
        </div>
    </div>
 <% end %>
</div>

app/views/attendance_informations/new.html.erb
<div class="container">
    <% if member_signed_in? %>
        <h2><%= "#{current_member.first_name} #{current_member.last_name}" %></h2>
    <% end %>
</div>
<h2 class="text-center">現在時刻</h2>
<h3 id="RealtimeClockArea" class="text-center"></h3>
<div class="container">
    <div class="row">
        <div class="col-md-6 mb-3 mb-md-0">
            <%= link_to '出勤', time_in_path, class: 'btn btn-primary btn-block' %>
        </div>
        <div class="col-md-6">
            <%= link_to '退勤', time_out_path, class: 'btn btn-danger btn-block' %>
        </div>
    </div>
    <hr>
    <div class="flex-box">
         <% @ais.each do |ai| %>
         <div class="flex-line">
           <div class="flex-box1">

                    <div class="flex-label">出勤</div>
                    <small><%= l ai.time_in.in_time_zone('Tokyo'), format: :original %></small>
           </div>
         <div class="flex-box1">
          <div class="flex-label">退勤</div>

            <% unless ai.time_out.nil? %>
                <small><%= l ai.time_out.in_time_zone('Tokyo'), format: :original %></small>
            <% else %>
                <small class="text-danger">打刻なし</small>
            <% end %>
        </div>
        </div>
      <% end %>
    </div>
</div>

app/views/attendance_informations/show.html.erb
<div class="container">
  <% unless @ai.approval_history.nil? %>
<h3>理由</h3>
  <div class="row">
    <div class="col">
      承認者名
      <div><%= @ai.approval_history.admin.first_name %>
      <%= @ai.approval_history.admin.last_name %></div>
    </div>
    <div class="col">
      ステータス
      <p><%= @ai.status_i18n %></p>
    </div>
    <div class="col">
      承認理由
      <%= simple_format(@ai.approval_history.reason) %>
    </div>
  </div>
</div>

<!--<p><%= @ai.status_i18n %></p>-->
<!--<% unless @ai.approval_history.nil? %>-->
<!--  <p><%= @ai.approval_history.admin.first_name %></p>-->
<!--  <p><%= @ai.approval_history.admin.last_name %></p>-->

<!--  <%= simple_format(@ai.approval_history.reason) %>-->
<!--<% end %>-->
<% end %>