config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  devise_for :members
  namespace :admins do
    resources :members, only: [:new, :create, :index, :show, :edit,:update,:destroy]
    resources :attendance_informations
    resources :work_scheduleds,only: [:index,:show,:edit,:update,:destroy]
  end
  resources :members, only: [:show, :update]

  root to: "homes#index"

  get '/time_in', to: 'attendance_informations#time_in'
  get '/time_out', to: 'attendance_informations#time_out'

  # post '/' => 'attendance_informations#create'
  # get '/time_out' => 'attendance_informations#new'
  # patch '/time_out' => 'attendance_informations#new'
  # get '/attendance' => 'attendance_informations#index'
  # get '/attendance/:id' => 'attendance_informations#edit'
  # patch '/attendance/:id' => 'attendance_informations#update'
  # get '/attendance_informations' => 'attendance_informations#show'

  resources :work_scheduleds,only: [:index,:new,:create]
  resources :attendance_informations
  # get 'charts/index'
  resources :charts,only: [:index, :edit, :update, :destroy]

end

app/views/layouts/_error_messages.html.erb
<% if errors.any? %>

<div id="error_explanation">
  <small><%= errors.count %>件のエラーが発生しました</small>
  <ul>
    <% errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LPD Attendance system</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width,initial-scale=1">

  </head>

  <body>

  <nav class="navbar navbar-expand-md navbar-light bg-light">

    <%= link_to "LPD Attendance system", root_path, class: "navbar-brand" %>
    <!--<a class="navbar-brand" href="#">LPD Attendance system</a>-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">

        <% if member_signed_in? %>
          <li class="nav-item">
            <%= link_to  "打刻履歴", attendance_informations_path,class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "稼働一覧",charts_path(year: Date.current.strftime("%Y"), month: Date.current.strftime("%m")), class: 'nav-link' %>
          </li>
          <li class="nav-item">
             <%= link_to "稼働予定日", work_scheduleds_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
             <%= link_to "マイページ", member_path(current_member), class: 'nav-link' %>
          </li>
           <li class="nav-item">
            <%= link_to "Memberログアウト", destroy_member_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% end %>

        <% if admin_signed_in? %>
          <li class="nav-item">
          <%= link_to  "メンバー一覧", admins_members_path,class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "稼働日", admins_work_scheduleds_path(year: Date.current.strftime("%Y"), month: Date.current.strftime("%m")),class: 'nav-link' %>
            </li>
              <li class="nav-item">
            <%= link_to "Adminログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% end %>

        <% unless admin_signed_in? || member_signed_in? %>
          <li class="nav-item">
            <%= link_to "Adminログイン", new_admin_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Memberログイン", new_member_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
    <div class="container">
      <% unless flash[:notice].blank? %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>
      <% unless flash[:alart].blank? %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>